# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-25 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('current_status', models.CharField(choices=[('open', 'open'), ('pending', 'pending'), ('in_process', 'in_process'), ('resolved', 'resolved'), ('closed', 'closed')], max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
